#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'''
Dicts and lists of music-related subreddits
'''

# credit to the music wiki https://www.reddit.com/r/music/wiki/musicsubreddits
# for most of this.
subreddit_genres = {
    'classical': (
        'composer', 'Baroque', 'classicalmusic', 'contemporary', 'ConcertBand',
        'choralmusic', 'chambermusic', 'EarlyMusic', 'earlymusicalnotation',
        'ElitistClassical', 'icm', 'opera', 'orchestra', 'bach'
    ),

    'rockmetal': (
        '80sHardcorePunk', '90sAlternative', '90sPunk', '90sRock',
        'Alternativerock', 'altcountry', 'AORmelodic', 'ausmetal',
        'BlackMetal', 'Bluegrass', 'blues', 'bluesrock', 'Boneyard',
        'CanadianClassicRock', 'CanadianMusic', 'ClassicRock', 'country',
        'christcore', 'crunkcore', 'Deathcore', 'Deathmetal', 'Djent',
        'doommetal', 'Drone', 'Emo', 'EmoScreamo', 'epicmetal', 'flocked',
        'folk', 'folkmetal', 'FolkPunk', 'folkrock', 'folkunknown',
        'GaragePunk', 'GothicMetal', 'grunge', 'Hardcore', 'HardRock',
        'horrorpunk', 'indie_rock', 'jrock', 'krautrock', 'LadiesofMetal',
        'mathrock', 'melodicdeathmetal', 'MelodicMetal', 'MetalNews',
        'Metalmusic', 'Metal', 'Metalcore', 'ModernRockMusic', 'monsterfuzz',
        'neopsychedelia', 'NewWave', 'noiserock', 'numetal', 'pianorock',
        'poppunkers', 'PostHardcore', 'postrock', 'PowerMetal', 'powerpop',
        'progmetal', 'progrockmusic', 'psychedelicrock', 'punk',
        'Punkskahardcore', 'Punk_Rock', 'rock', 'shoegaze',
        'stonerrock', 'symphonicblackmetal', 'symphonicmetal',
        'truethrash', 'Truemetal', 'OutlawCountry', 'WomenRock', 'metaljerk',
        'MetalPorn', 'TechnicalDeathMetal', 'falsemetal', '00sRock', 'softrock',
        'rockabilly', 'postmetal', 'vinylcore', 'BABYMETAL', 'IndieFolk',
        'indie', 'IndieWok',  'indieheads', 'melodichardcore',

        'BetweenTheBuriedAndMe', 'TheFence', 'Nirvana', 'greenday',
        'GunsNRoses', 'Megadeth', 'Metallica', 'Muse', 'Opeth', 'Slayer',
        'Slipknot', 'qotsa', 'Foofighters', 'arcticmonkeys',
    ),

    'electronic': (
        'acidhouse', 'ambientmusic', 'AStateOfTrance', 'AtmosphericDnB',
        'boogiemusic', 'breakbeat', 'breakcore', 'brostep', 'chicagoEDM',
        'chicagohouse', 'chillout', 'Chipbreak', 'chiptunes', 'complextro',
        'darkstep', 'deephouse', 'DnB', 'dnbproduction', 'dubstep', 'EDM',
        'electronicdancemusic', 'ElectronicJazz', 'ElectronicBlues',
        'electrohouse', 'electronicmagic', 'electronicmusic',
        'electropop', 'electroswing', 'fidget', 'filth',
        'frenchelectro', 'frenchhouse', 'funkhouse', 'fusiondancemusic',
        'futurebeats', 'FutureFunkAirlines', 'FutureGarage', 'futuresynth',
        'gabber', 'glitch', 'glitchop', 'grime', 'happyhardcore', 'hardhouse',
        'hardstyle', 'house', 'idm', 'ItaloDisco',
        'latinhouse', 'LiquidDubstep', 'minimal', 'mixes',
        'moombahcore', 'nightstep', 'OldskoolRave',
        'plunderphonics', 'psybient', 'PsyBreaks', 'psytrance', 'purplemusic',
        'raggajungle', 'realdubstep', 'skweee', 'swinghouse', 'tech_house',
        'Techno', 'trance', 'tranceandbass', 'tribalbeats',
        'TropicalHouse', 'ukfunky', 'witchhouse', 'wuuB',
        'synthesizers', 'synthrecipes', 'strobe', 'strobecirclejerk',
        'bigbeat', 'shallowhouse', 'ElectricForest', 'House', 'BigRoom',
        'electricdaisycarnival', 'Monstercat', 'MovementDEMF',

        'skrillex', 'deadmau5', 'knifeparty', 'ericprydz',
        'CounterPointFestival', 'DaftPunk', 'EDCNY', 'Zomboy',
    ),

    'hiphop' : (
        '80sHipHop', '90sHipHop', 'asianrap', 'backspin', 'BayRap',
        'ChapHop', 'ChiefKeef', 'DrillandBop', 'Gfunk', 'hiphopheads', 'NYrap',
        'rap', 'rapverses', 'rhymesandbeats', 'hiphop101',
        'hiphop', 'GermanRap', 'makinghiphop', 'HipHopImages', 'hiphopsamples',
        'hiphopvinyl', 'hiphoptruth', 'LofiHipHop', 'Hiphopcirclejerk',
        'therappening', 'OGHHH',

        'Eminem', 'ChanceTheRapper', 'Kanye', 'KendrickLamar', 'TeamSESH',
    )
}

music_subreddits = tuple( [subreddit for sublist in subreddit_genres.values() for subreddit in sublist] )\
+ (
    # Manually excluded subreddits
    'electrohiphop', 'raprock', 'industrialmetal', 'industrialmusic',
    'synthrock', 'headphones', 'nin', 'violinist', 'abletonlive', 'funk',
    'futurebass', 'altrap', 'trapmuzik', 'trap', 'trapproduction',
    'nightwish', 'Savant', 'lapfoxtrax', 'wakarusa', 'LightningInABottle',
    'TomorrowWorld', 'Tomorrowland', 'MonstercatCringe', 'themonsterkittens',
    'subgenreid', 'burial', 'porterrobinson', 'outrun',
    'Musicthemetime', 'SundayMorningMusic', 'ChristianMusic', 'BattleMusic',
    'nintendomusic', 'crappymusic', 'WussyMusic', 'trueMusic',
    'experimentalmusic', 'musicforsex', 'askmusic', 'INTPmusic', 'UnsentMusic',
    'rocksmith', 'Cyberpunk_Music','musicofthespheres', 'musicmakers_ja',
    'SRSMusic', 'Adventurermusic', 'Dronemusic', 'guitarpedals',
    'heavyvinyl', 'DevinTownsend', 'Bandnames', 'bobdylan',
    'soundgarden', 'alkalinetrio', 'Cyberpunk', 'horn', 'bonnaroo',
    'aphextwin', 'drumcorps', 'Pendulum', 'bassvoices', 'bassnectar',
    'twentyonepilots', 'BudgetAudiophile', 'Beatmatch', 'sadboys', 'aves',
    'rapbattles','mashups', 'vintageaudio', 'xTrill',
    'edmproductioncirclejerk', 'avesNYC', 'TranceCirclejerk',
    'dancegavindance', 'RiotFest', 'metalguitar', 'metalmusicians',
    'leakthreads', 'AdvancedProduction', 'edmproduction', 'TaylorSwift', 
    'donaldglover', 'freshalbumart', 'modular', 'Coachella', 'DJsCirclejerk',
    'Lollapalooza', 'bisco', 'maschine', 'TheWeeknd', 'livesound',
    'deathgrips', 'edmprodcirclejerk', 'TameImpala', 'macdemarco',
    'guitarporn', 'SakuraGakuin', 'guitars', 'avengedsevenfold',
    'Dreamtheater', 'Sufjan', 'Guitar', 'VinylCollectors', 'Recordings',
    "FireflyFestival", 'RapWars',

    # All 'misc' music subreddits
    '2010sMusic', '2000sMusic', '90smusic', '80smusic', '70smusic', '60sMusic',
    '50sMusic', 'AfricanMusic', 'afrobeat', 'balkanbrass', 'balkanmusic',
    'britpop', 'Irishmusic', 'ItalianMusic', 'jpop', 'kpop', 'RoMusic', 'spop',
    'UKbands', 'WorldMusic', '70s', 'Acappella', 'AcousticCovers',
    'animemusic', 'boomswing', 'bossanova', 'carmusic', 'concerts',
    'chillmusic', 'cpop', 'Complextro', 'dembow', 'disco', 'DreamPop', 'dub',
    'Elephant6', 'ETIMusic', 'Exotica', 'FilmMusic', 'FunkSouMusic',
    'gamemusic', 'GamesMusicMixMash', 'GunslingerMusic', 'GypsyJazz',
    'jambands', 'Jazz', 'JazzFusion', 'JazzInfluence',
    'listentoconcerts', 'klezmer', 'lt10k', 'MedievalMusic', 'MelancholyMusic',
    'minimalism_music', 'motown', 'MusicForConcentration', 'muzyka', 'NuDisco',
    'oldiemusic', 'OldiesMusic', 'pianocovers', 'PopMusic', 'PoptoRock',
    'QuietStorm', 'rainymood', 'recordstorefinds', 'reggae', 'remixxd',
    'RetroMusic', 'rnb', 'rootsmusic', 'SalsaMusic', 'Ska', 'Soca',
    'songbooks', 'Soulies', 'SoulDivas', 'SoundsVintage', 'SpaceMusic',
    'swing', 'Tango', 'TheRealBookVideos', 'TouhouMusic', 'TraditionalMusic',
    'treemusic', 'triphop', 'vaporwave', 'VintageObscura', 'vocaloid',
    'audioinsurrection', 'albumaday', 'albumoftheday', 'Albums',
    'albumlisteners', 'bassheavy', 'BinauralMusic', 'Catchysongs', 'Chopping',
    'CircleMusic', 'CoverSongs', 'DANCEPARTY', 'danktunes',
    'deepcuts', 'FemaleVocalists',
    'festivals', 'findaband', 'FitTunes', 'FreeAlbums', 'freemusic', 'Frisson',
    'gameofbands', 'GayMusic', 'germusic', 'gethightothis',
    'GuiltyPleasureMusic', 'HeadNodders', 'heady', 'HeyThatWasIn',
    'HighFidelity', 'ifyoulikeblank', 'Instrumentals',
    'ipm', 'IsolatedVocals', 'LeeHallMusic', 'LetsTalkMusic',
    'listentoconcerts', 'listentomusic', 'listentonews', 'listentothis',
    'ListenToUs', 'livemusic', 'llawenyddhebddiwedd', 'LongerJams', 'Lyrics',
    'mainstreammusic', 'makemeaplaylist', 'MiddleEasternMusic', 'MLPtunes',
    'Music', 'MusicAlbums', 'musicsuggestions', 'MusicToSleepTo',
    'musicvideos', 'NameThatSong', 'NewAlbums', 'newmusic', 'onealbumaweek',
    'partymusic', 'RedditOriginals', 'RepublicOfMusic', 'RoyaltyFreeMusic',
    'runningmusic', 'Samples', 'ScottishMusic', 'songwriterscircle',
    'SpotifyMusic', 'ThemVoices', 'unheardof', 'WhatIListenTo',
    'WTFMusicVideos', 'AlbumArtPorn', 'albumreviews', 'Audio', 'audiophile',
    'AustinMusicians', 'bandmembers', 'CarAV', 'cassetteculture',
    'Cd_collectors', 'ConcertTickets', 'germusic', 'glastonbury_festival',
    'ICoveredASong', 'ifyoulikeblank', 'independentmusic', 'ineedasong',
    'japanesemusic', 'Jazzguitar', 'koreanmusic', 'LubbockMusicians', 'mixcd',
    'musiccritics', 'MusicalComedy', 'musicessentials', 'MusicEventMeetUp',
    'musicfestivals', 'musicnews', 'MusiciansBlogs', 'Musicians', 'NeedVocals',
    'OSOM', 'performer', 'RecordClub', 'recordstore', 'redditmusicclub',
    'Rockband', 'RockbandChallenges', 'TheSongRemainsTheSame',
    'TouringMusicians', 'vinyl', 'VinylReleases', 'WeAreTheMusicMakers',
    '300Songs', 'AcousticOriginals', 'ICoveredASong',
    'independentmusic', 'MusicCritique', 'MusicInTheMaking', 'MyMusic',
    'RadioReddit', 'ratemyband', 'Songwriters', 'TheseAreOurAlbums',
    'ThisIsOurMusic', 'UserProduced', 'WereOnSpotify', 'WhiteLabels', '311',
    'ADTR', 'AliciaKeys', 'ArcadeFire', 'ArethaFranklin', 'APerfectCircle',
    'TheAvettBrothers', 'BaysideIsACult', 'TheBeachBoys', 'beatles',
    'billytalent', 'Blink182', 'BMSR', 'boniver', 'brandnew',
    'BruceSpringsteen', 'ChristinaAguilera', 'cityandcolour',
    'Coldplay', 'CutCopy', 'TheCure', 'DavidBowie',
    'DeathCabforCutie', 'DeepPurple', 'deftones', 'DieAntwoord', 'DMB',
    'elliegoulding', 'empireofthesun', 'EnterShikari', 'Evanescence', 'feedme',
    'FirstAidKit', 'flaminglips', 'franzferdinand', 'gorillaz', 'gratefuldead',
    'Incubus', 'JackWhite', 'JanetJackson',
    'John_frusciante', 'kings_of_leon', 'Korn', 'ladygaga', 'lanadelrey',
    'lennykravitz', 'Led_Zeppelin', 'lorde', 'Macklemore', 'Madonna',
    'Manowar', 'MariahCarey', 'MattAndKim', 'MGMT',
    'MichaelJackson', 'MinusTheBear', 'ModestMouse', 'Morrissey',
    'MyChemicalRomance', 'NeilYoung', 'NIN', 'NOFX',
    'oasis', 'OFWGKTA', 'OutKast', 'panicatthedisco', 'pearljam',
    'phish', 'Pinback', 'pinkfloyd', 'porcupinetree', 'prettylights',
    'Puscifer', 'Queen', 'radiohead', 'RATM', 'RedHotChiliPeppers',
    'The_Residents', 'RiseAgainst', 'rush', 'SigurRos', 
    'SmashingPumpkins', 'SparksFTW', 'TeganAndSara', 'TheKillers',
    'TheOffspring', 'TheStrokes', 'TheMagneticZeros', 'tragicallyhip',
    'ToolBand', 'U2Band', 'Umphreys', 'UnicornsMusic', 'velvetunderground',
    'Ween', 'weezer', 'WeirdAl', 'yesband', 'Zappa', 'AlbumArtPorn',
    'BandPorn', 'concertporn', 'guitarporn', 'InstrumentPorn', 'MetalMemes',
    'MusicBattlestations', 'musicpics', 'GrooveSharkPlaylists', 'DJs',
    'PirateRadio', 'spotify', 'Turntablists', 'abletonclass', 'bandmembers',
    'bassLessons', 'DancePerformance', 'grooveshark',
    'Ethnomusicology', 'ExplainThisSong', 'guitarlessons', 'Learnmusic',
    'MusicEd', 'musicindustry', 'MusicInstructor', 'musicology', 'musictheory',
    'solresol', 'tabs', 'Accordion', 'banjo', 'Bass', 'bassplaying', 'Bassoon',
    'beatbox', 'brass', 'Cello', 'Clarinet', 'classicalguitar', 'Concertina',
    'DoubleBass', 'Drummers', 'drums', 'Flute', 'guitar', 'GuitarPlaying',
    'hammondorgan', 'handpan', 'harmonica', 'Horn', 'keys', 'Luthier',
    'Mandolin', 'Oboe', 'Ocarina', 'Percussion', 'Percussionists', 'piano',
    'Piccolo', 'PlayingGuitar', 'Recorder', 'saxophone', 'saxophonics',
    'singing', 'Telecaster', 'Trombone', 'trumpet', 'tuba',
    'ukulele', 'viola', 'Violinist', 'audioengineering',
    'FL_Studio', 'ableton', 'AbletonLive', 'AudioPost', 'Cubase',
    'futurebeatproducers', 'GameAudio', 'linuxaudio', 'LocationSound',
    'Logic_Studio', 'MaxMSP', 'ProductionLounge', 'Protools', 'RateMyAudio',
    'Reaper', 'Reasoners', 'Remix', 'Renoise', 'Samplehunters', 'SongStems',
    'VSTi', 'DIYGear', 'Gear4Sale', 'GuitarPedals', 'skullcandy',
)

genres = tuple( subreddit_genres.keys() )
